### ISSUE TITLE
Usage example doesn't match real output

### ISSUE THREAD

**Issue by fregante** [sindresorhus/pkg-dir-cli#1]
The `--cwd` option doesn't seem to work for me, but simply passing a path does (which is preferable anyway)

<img width="560" alt="screen shot 2016-08-17 at 16 38 22" src="https://cloud.githubusercontent.com/assets/1402241/17731771/b040d6fa-6423-11e6-9e98-dd79a7527fae.png">

**Comment by SamVerschueren** [comment]
Good catch!

This cli cals [pkgDir.sync](https://github.com/sindresorhus/pkg-dir-cli/blob/master/cli.js#L22) with the input and the flags. But it seems that `pkg-dir` doesn't have [options](https://github.com/sindresorhus/pkg-dir#pkgdirsynccwd) and it just accepts the `cwd` as main argument.
